---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sugar.kubeblocks.io
  resources:
  - apecloudmysqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sugar.kubeblocks.io
  resources:
  - apecloudmysqls/finalizers
  verbs:
  - update
- apiGroups:
  - sugar.kubeblocks.io
  resources:
  - apecloudmysqls/status
  verbs:
  - get
  - patch
  - update
