# permissions for end users to view apecloudmysqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: apecloudmysql-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubeblocks-sugar
    app.kubernetes.io/part-of: kubeblocks-sugar
    app.kubernetes.io/managed-by: kustomize
  name: apecloudmysql-viewer-role
rules:
- apiGroups:
  - sugar.kubeblocks.io
  resources:
  - apecloudmysqls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sugar.kubeblocks.io
  resources:
  - apecloudmysqls/status
  verbs:
  - get
